### ISSUE TITLE
А можно немножко кодревью?)

### ISSUE THREAD

**Issue by loysagienn** [alexkorep/react-array-to-tree#1]
Текущая версия, кажется, имеет недостатки:

- Функция мутирует переданный снаружи аргумент, и это довольно неприятный сайдэффект, который не ожидаешь от внешней библиотеки
- На каждый вложенный компонент создаётся дополнительный компонент-обёртка, вложенность возрастает вдвое, кажется это не очень оптимально

Есть предложение вот такой реализации без этих недостатков:
```js
const BuildComponetTree = (providers) => ({ children }) => {
  const lastIndex = providers.length - 1;
  let activeChildren = children;
  
  for (let i = lastIndex; i >= 0; i--) {
    const [Provider, props] = providers[i];

    activeChildren = <Provider {...(props || {})}>{activeChildren}</Provider>;
  }

  return activeChildren;
};
```

**Comment by infodusha** [comment]
Я пришел со своим улучшением:
```typescript
export function buildProviderTree(...providers: JSX.Element[]) {
  return function ProviderTree({ children }: React.PropsWithChildren) {
    const lastIndex = providers.length - 1;
    let activeChildren = children;

    for (let i = lastIndex; i >= 0; i--) {
      const element = providers[i];
      activeChildren = { ...element, props: { ...element.props, children: activeChildren } };
    }

    return activeChildren;
  };
}
```

Тут появилась проверка типов за счет того что теперь мы передаем сразу JSX.
(вначале была идея сделать просто поддержку типов варианта выше но как в итоге сделал явно проще.

**Comment by alexkorep** [comment]
Кидайте PR :-)
